name: utopia_arch
description: Utopia libs - complete architecture (including hooks, widgets, utils, reporter, collections, validation)
version: 0.5.0+37
homepage: https://github.com/Utopia-USS/utopia-flutter

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  utopia_utils: ^0.3.2
  utopia_hooks: ^0.4.11
  utopia_reporter: ^0.1.0+4
  utopia_collections: ^0.1.0+1
  utopia_validation: ^0.1.0+3
  utopia_widgets: ^0.1.1+2

  page_transition: ^2.0.2
  shared_preferences: ^2.0.7
  injector: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  utopia_lints: ^0.0.3+2
