name: utopia_arch
description: Utopia libs - complete architecture (including hooks, widgets, utils, reporter, collections, validation)
version: 0.4.8+2
homepage: https://github.com/Utopia-USS/utopia-flutter

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  utopia_utils: ^0.2.28
  utopia_hooks: ^0.3.12+1
  utopia_reporter: ^0.0.1
  utopia_collections: ^0.0.1
  utopia_validation: ^0.0.1
  utopia_widgets: ^0.0.10+28

  page_transition: ^2.0.2
  shared_preferences: ^2.0.7
  injector: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  utopia_lints: ^0.0.3+1
