name: utopia_arch
description: Utopia USS libs - generic architecture components
version: 0.4.4
homepage: https://github.com/Utopia-USS/utopia-flutter

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  utopia_utils: ^0.2.27
  utopia_hooks: ^0.3.10
  flutter_hooks: ^0.18.0
  page_transition: ^2.0.2
  shared_preferences: ^2.0.7
  injector: ^2.0.0
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  utopia_lints: ^0.0.3+1
