name: utopia_arch
description: Utopia USS libs - generic architecture components
version: 0.3.4+1
homepage: https://github.com/Utopia-USS/utopia-flutter

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  utopia_utils: ^0.2.10
  utopia_hooks: ^0.3.0
  flutter_hooks: ^0.18.0
  page_transition: ^2.0.2
  shared_preferences: ^2.0.7
  injector: ^2.0.0
  provider: ^6.0.0

dev_dependencies:
  utopia_lints: ^0.0.1+1