name: utopia_rest
description: Utopia USS libs - REST API support with Dio
version: 0.0.6
homepage: https://github.com/Utopia-USS/utopia-flutter

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  utopia_utils: ^0.2.13
  dio: ^4.0.0

dev_dependencies:
  utopia_lints: ^0.0.1+1