name: utopia_localization_generator_example
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  utopia_localization_annotation:
    path: ../../annotation
  utopia_localization_utils:
    path: ../../utils

  intl: ^0.19.0
  file_picker: ^8.0.5

dev_dependencies: 
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  utopia_localization_generator:
    path: ../

flutter:
  uses-material-design: true
