name: utopia_validation
description: Utopia USS libs - generic architecture components
version: 0.1.0
homepage: https://github.com/Utopia-USS/utopia-flutter

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  utopia_utils: ^0.3.0

dev_dependencies:
  utopia_lints: ^0.0.3+1
