name: utopia_flutter

packages:
  - packages/**

scripts:
  release: melos version && melos publish --no-dry-run && git push --follow-tags
  release:force: melos version -y && melos publish -y --no-dry-run && git push --follow-tags