name: utopia_localization_generator
description: Utopia USS libs - Localization - Google Sheet-based localization code generator.
version: 0.0.1
homepage: https://github.com/Utopia-USS/utopia-flutter

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  utopia_localization_annotation: ^0.0.1
  utopia_localization_builder: ^0.0.1

  http: ^1.2.1
  meta: ^1.3.0
  csv: ^6.0.0
  source_gen: ^1.0.0
  build: ^2.0.0
  analyzer: ^6.4.1

dev_dependencies:
  build_runner: ^2.0.2
