name: utopia_widgets_example
description: Demonstrates how to use the utopia_widgets plugin.
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  utopia_widgets:
    path: ../

  utopia_utils: ^0.3.1+1
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
