name: utopia_widgets
description: Utopia USS libs - simple, generic widgets
version: 0.0.10+22
homepage: https://github.com/Utopia-USS/utopia-flutter

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  utopia_utils: ^0.2.24+2
dev_dependencies:
  utopia_lints: ^0.0.3+1