name: utopia_hooks
description: Utopia USS libs - basic and complex hooks (including SubmitState, ComputedState and supporting widgets)
version: 0.2.1+3
homepage: https://github.com/Utopia-USS/utopia-flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  utopia_utils: ^0.2.1
  flutter_hooks: ^0.18.0
  provider: ^6.0.0
  equatable: ^2.0.3