name: utopia_hooks
description: Utopia USS libs - basic and complex hooks (including SubmitState, ComputedState and supporting widgets)
version: 0.3.4+1
homepage: https://github.com/Utopia-USS/utopia-flutter

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  utopia_utils: ^0.2.22+1
  flutter_hooks: ^0.18.0
  provider: ^6.0.0
  equatable: ^2.0.3
  async: ^2.5.0
  fast_immutable_collections: ^7.0.3

dev_dependencies:
  utopia_lints: ^0.0.3