name: utopia_hooks
description: Utopia libs - basic and complex hooks (including SubmitState, ComputedState and supporting widgets)
version: 0.3.12+1
homepage: https://github.com/Utopia-USS/utopia-flutter

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  utopia_utils: ^0.2.28
  utopia_collections: ^0.0.1
  utopia_validation: ^0.0.1

  equatable: ^2.0.3
  async: ^2.5.0
  meta: ^1.10.0

dev_dependencies:
  flutter_test:
      sdk: flutter
  test: ^1.24.9
  utopia_lints: ^0.0.3+1