name: utopia_connectivity
description: Utopia USS libs - ConnectivityState
version: 0.0.4+21
homepage: https://github.com/Utopia-USS/utopia-flutter

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  utopia_hooks: ^0.3.5+3
  connectivity_plus: ^1.1.0

dev_dependencies:
  utopia_lints: ^0.0.3+1