name: utopia_connectivity
description: Utopia USS libs - ConnectivityState
version: 0.0.5+15
homepage: https://github.com/Utopia-USS/utopia-flutter

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  utopia_utils: ^0.2.27
  utopia_hooks: ^0.3.11
  connectivity_plus: ^3.0.3

dev_dependencies:
  utopia_lints: ^0.0.3+1