name: utopia_localization_template
description: Utopia USS libs - Localization - Internal library used both by utopia_localization_annotation and utopia_localization_generator.
version: 0.0.2
homepage: https://github.com/Utopia-USS/utopia-flutter

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  intl: ">= 0.17.0 <1.0.0"
