name: utopia_reporter
description: Utopia libs - Reporter architecture
version: 0.1.0-dev.0
homepage: https://github.com/Utopia-USS/utopia-flutter

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  utopia_utils: ^0.3.0-dev.0
  logger: ^1.4.0

dev_dependencies:
  utopia_lints: ^0.0.3+1