name: utopia_localization_annotation
description: Utopia USS libs - Localization - Annotations for utopia_localization_generator.
version: 0.0.2
homepage: https://github.com/Utopia-USS/utopia-flutter

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  utopia_localization_template: ^0.0.2
