name: utopia_firebase_crashlytics
description: Utopia USS libs - firebase crashlytics setup and Reporter implementation
version: 0.1.4+20
homepage: https://github.com/Utopia-USS/utopia-flutter

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  utopia_reporter: ^0.0.1
  firebase_core: ^2.1.1
  firebase_crashlytics: ^3.0.4

dev_dependencies:
  utopia_lints: ^0.0.3+1