name: utopia_firebase_crashlytics
description: Utopia USS libs - firebase crashlytics setup and Reporter implementation
version: 0.1.3+6
homepage: https://github.com/Utopia-USS/utopia-flutter

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  utopia_utils: ^0.2.16+1
  firebase_core: ^1.6.0
  firebase_crashlytics: ^2.2.1

dev_dependencies:
  utopia_lints: ^0.0.1+2