name: utopia_firebase_crashlytics
description: Utopia USS libs - firebase crashlytics setup and Reporter implementation
version: 0.2.0+3
homepage: https://github.com/Utopia-USS/utopia-flutter

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  utopia_reporter: ^0.1.0+3
  firebase_core: ^3.1.1
  firebase_crashlytics: ^4.0.2

dev_dependencies:
  utopia_lints: ^0.0.3+2