name: utopia_utils
description: Utopia USS libs - generic utils (including extensions, and Reporter architecture)
version: 0.3.1
homepage: https://github.com/Utopia-USS/utopia-flutter

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  intl: ">=0.17.0 <0.20.0"
  meta: ^1.10.0

dev_dependencies:
  utopia_lints: ^0.0.3+2