name: utopia_utils
description: Utopia USS libs - generic utils (including extensions, and Reporter architecture)
version: 0.2.7
homepage: https://github.com/Utopia-USS/utopia-flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.17.0
  logger: ^1.1.0
  fast_immutable_collections: ^7.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

