name: utopia_utils
description: Utopia USS libs - generic utils (including extensions, and Reporter architecture)
version: 0.2.20
homepage: https://github.com/Utopia-USS/utopia-flutter

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.17.0
  logger: ^1.1.0
  fast_immutable_collections: ^7.0.3

dev_dependencies:
  utopia_lints: ^0.0.1+2